title:  The Qualitative Self
author: C-Brennan-Poole
affiliatation: with Wind
email:  chief@chasingthewindllc.com
description: The Qualitative Self a course of life's work
# social links
twitter_username: OUDcollective
github_username: OUDcollective
linkedin_username: oudcollective
linkedin_username: c-brennan-poole
pinterest_username: withWindllc
medium_username: C.Brennan.Poole
dribbble_username: C-Brennan-Poole
crunchbase_username: c-brennan-poole
facebook_username: inthebusinessbusiness
instagram_username: twenty20times
snapchat_username: cbrennanp
quora_username: c-brennan-poole
startupschool_username: withWind
show_excerpts: true # set to false to remove excerpts on the homepage
creative commons: (CC BY-SA)

theme: jekyll-theme-architect

