title:  Portfolio-Proficiency-Project
author: C-Brennan-Poole
email:  CBrennanP@chasingthewindllc.com
description: > # this means to ignore newlines until "baseurl:"
C Brennan is a lifetime student and natural leader. The Chasing the Wind brand is very well in it's infancy, but it is almost impossible to fathom the brand failing with the sustainability / Toyota Way Management methodolog Brennan has begun to instill in everything he does. 

# social links
twitter_username: @OUDcollective
github_username:  OUDcollective

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
