title:  God—centered—Human Design-Thinking Ops Strategist
author: C-Brennan-Poole
email:  chief@chasingthewindllc.com
description: > # this means to ignore newlines until "baseurl:"
                Chasing the wind, LLC is a ethical professional option.
# social links
twitter_username: OUDcollective
github_username:  OUDcollective

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
