title:  Qualitative-Self
author: cbrennanpoole
email:  gitactionable@withWind.llc
description: > # this means to ignore newlines until "baseurl:"
                C Brennan Poole | Course of Life's Work - Plain English for CV
# social links
twitter_username: cbrennanpoole
github_username:  cbrennanpoole


show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
