title:  Portfolio-Proficiency-Project
author: C-Brennan-Poole
email:  CBrennanP@chasingthewindllc.com
description: > # this means to ignore newlines until "baseurl:"
C Brennan is a lifetime student and natural leader of Chasing the Wind, llc
# social links
twitter_username: @OUDcollective
github_username:  OUDcollective

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
