title:  Creative Ops Strategist
author: C-Brennan-Poole
email:  chief@chasingthewindllc.com
description: > # this means to ignore newlines until "baseurl:"
                Hey! I'm C Brennan and this is my body of work. Hiring? Let's connect +1 678-338-7339
# social links
twitter_username: OUDcollective
github_username:  OUDcollective

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
